AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
    
  HelloFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.hello
      Runtime: nodejs12.x
      CodeUri: ./hello
      Policies: 
        - LambdaInvokePolicy:
            FunctionName: 
              !Ref OnSuccessFunction
        - LambdaInvokePolicy:
            FunctionName: 
              !Ref OnFailureFunction
      Events:
        InvokeFunction:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket
            Events: s3:ObjectCreated:*

  SrcBucket:
    Type: AWS::S3::Bucket
  
  OnSuccessFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.success
      Runtime: nodejs12.x
      CodeUri: ./success

  OnFailureFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.failure
      Runtime: nodejs12.x
      CodeUri: ./failure
    
  EventInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
        FunctionName: !Ref HelloFunction
        Qualifier: "$LATEST"
        MaximumEventAgeInSeconds: 600
        MaximumRetryAttempts: 0
        DestinationConfig:
          OnSuccess:
            Destination: !GetAtt OnSuccessFunction.Arn
          OnFailure:
            Destination: !GetAtt OnFailureFunction.Arn
  
Outputs:
  Region:
    Description: "Region"
    Value: !Ref AWS::Region

  S3Bucket:
    Description: "Bucket"
    Value: !Ref SrcBucket